require 'rack'
require 'thin'
require 'bundler/setup'
require 'nanoc3/tasks'
require 'nanoc3/cli'
require 'compass'
Compass.add_project_configuration('./lib/compass.rb')

desc "Runs autocompile/preview"
task :preview do
  # Run base
  Nanoc3::CLI::Base.shared_base.run(["autocompile","--handler=thin"])
end

desc "Runs compile/generate"
task :build do
  # Run base
  Nanoc3::CLI::Base.shared_base.run(["compile"])
end

desc 'Remove output files generated by nanoc3'
task :cleanup do
  # Load site
  site = Nanoc3::Site.new('.')
  if site.nil?
    $stderr.puts 'The current working directory does not seem to be a ' +
                 'valid/complete nanoc site directory; aborting.'
    exit 1
  end
  # Clean
  clean = ::Nanoc3::Tasks::Clean.new(site)
  clean.run
end
